import {Card, Link, Spinner} from "@heroui/react";
import {useEffect, useMemo, useState} from "react";

import {SearchHero} from "./components/SearchHero";
import {SiteHeader} from "./components/SiteHeader";
import type {GridMode} from "./components/CapabilityGrid";
import {FeatureStrip} from "./components/FeatureStrip";
import {ArrowUpRightIcon} from "./components/Icons";
import {
  matchesCapability,
  routeFromHash,
  shownCapabilities,
} from "./lib/data";
import {CapabilityPage} from "./pages/CapabilityPage";
import {IndexPage, type ResultsMode} from "./pages/IndexPage";
import {
  ChangesPage,
  ComparePage,
  MethodPage,
} from "./pages/ReferencePages";
import type {MirrorDatabase, Route} from "./types";

const STAR_STORAGE_KEY = "mcpMirrorStars";

function useRoute(): Route {
  const [route, setRoute] = useState(() => routeFromHash(window.location.hash));

  useEffect(() => {
    const onHashChange = () => {
      setRoute(routeFromHash(window.location.hash));
      window.scrollTo({top: 0, behavior: "instant"});
    };
    window.addEventListener("hashchange", onHashChange);
    return () => window.removeEventListener("hashchange", onHashChange);
  }, []);

  return route;
}

function readStars(): string[] {
  try {
    return JSON.parse(localStorage.getItem(STAR_STORAGE_KEY) ?? "[]") as string[];
  } catch {
    return [];
  }
}

function SiteFooter({database}: {database: MirrorDatabase}) {
  return (
    <footer className="site-footer">
      <div className="site-shell footer-inner">
        <section>
          <h2>MCP Mirror</h2>
          <p>Support tables for MCP tool-definition fidelity across agent frameworks.</p>
          <p>
            Created and maintained by{" "}
            <Link
              href="https://github.com/thierrypdamiba"
              target="_blank"
              rel="noopener noreferrer"
            >
              Thierry Damiba
            </Link>
            .
          </p>
          <p>
            Every cell is generated by a{" "}
            <Link
              href={`${database.repo || "https://github.com/thierrypdamiba/mcp-mirror"}/blob/main/src/mcp_mirror/diff.py`}
              target="_blank"
              rel="noopener noreferrer"
              aria-label="deterministic adapter diff source on GitHub, opens externally"
            >
              deterministic adapter diff
              <ArrowUpRightIcon width={13} height={13} />
            </Link>
            .
          </p>
          <p>
            Presentation adapted from{" "}
            <Link
              href="https://github.com/Fyrd/caniuse"
              target="_blank"
              rel="noopener noreferrer"
            >
              Can I use
            </Link>
            , CC BY 4.0.
          </p>
        </section>

        <section>
          <h2>Support the project</h2>
          <p>Corrections and new framework measurements are welcome.</p>
          <Link
            href={database.repo || "https://github.com/"}
            target="_blank"
            rel="noopener noreferrer"
          >
            Contribute on GitHub
          </Link>
          <p>Code: MIT<br />Data: CC BY 4.0</p>
        </section>

        <section>
          <h2>Site links</h2>
          <nav aria-label="Footer navigation">
            <Link href="#/">Home</Link>
            <Link href="#/changes">Measurement changes</Link>
            <Link href="#/compare">Compare frameworks</Link>
            <Link href="#/method">Method and defaults</Link>
          </nav>
        </section>

        <section>
          <h2>Legend</h2>
          <ul className="footer-legend">
            <li><i className="support-y" /> Present at capture boundary</li>
            <li><i className="support-n" /> Dropped during adaptation</li>
            <li><i className="support-a" /> Changed or retained elsewhere</li>
            <li><i className="support-u" /> Not yet measured</li>
          </ul>
        </section>
      </div>
    </footer>
  );
}

export default function App() {
  const [database, setDatabase] = useState<MirrorDatabase | null>(
    () => window.__MCP_MIRROR_DATA__ ?? null,
  );
  const [loadError, setLoadError] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const [resultsMode, setResultsMode] = useState<ResultsMode>("tables");
  const [gridMode, setGridMode] = useState<GridMode>("support");
  const [isFilterOpen, setIsFilterOpen] = useState(false);
  const [selectedCategories, setSelectedCategories] = useState<string[]>([]);
  const [stars, setStars] = useState<string[]>(readStars);
  const route = useRoute();

  useEffect(() => {
    if (window.__MCP_MIRROR_DATA__) {
      return;
    }
    const controller = new AbortController();
    fetch("./data/data-1.0.json", {signal: controller.signal})
      .then((response) => {
        if (!response.ok) {
          throw new Error(`Support data returned HTTP ${response.status}`);
        }
        return response.json() as Promise<MirrorDatabase>;
      })
      .then(setDatabase)
      .catch((error: unknown) => {
        if (error instanceof DOMException && error.name === "AbortError") {
          return;
        }
        setLoadError(error instanceof Error ? error.message : "Unknown error");
      });
    return () => controller.abort();
  }, []);

  useEffect(() => {
    if (!database) {
      return;
    }
    const capability =
      route.name === "capability"
        ? database.data[route.capabilityId]
        : undefined;
    document.title = capability
      ? `${capability.title.replaceAll("`", "")} | MCP Mirror`
      : `${route.name === "index" ? "MCP capability support" : route.name} | MCP Mirror`;
  }, [database, route]);

  const allCapabilities = useMemo(
    () => (database ? shownCapabilities(database) : []),
    [database],
  );
  const filteredCapabilities = useMemo(
    () =>
      allCapabilities.filter(
        (capability) =>
          matchesCapability(capability, query) &&
          (!selectedCategories.length ||
            capability.categories?.some((category) =>
              selectedCategories.includes(category),
            )),
      ),
    [allCapabilities, query, selectedCategories],
  );

  if (loadError) {
    return (
      <div className="load-state">
        <Card className="load-card">
          <Card.Header>
            <Card.Title>Support data could not be loaded</Card.Title>
            <Card.Description>{loadError}</Card.Description>
          </Card.Header>
          <Card.Content>
            <p>
              Run <code>npm run dev</code> for local development or{" "}
              <code>npm run build</code> to regenerate the published site.
            </p>
          </Card.Content>
        </Card>
      </div>
    );
  }

  if (!database) {
    return (
      <div className="load-state" role="status">
        <Spinner size="lg" />
        <span>Loading measured support data</span>
      </div>
    );
  }

  const capability =
    route.name === "capability"
      ? database.data[route.capabilityId]
      : undefined;

  const onSearchChange = (value: string) => {
    setQuery(value);
    if (route.name !== "index") {
      window.location.hash = "#/";
    }
  };

  const toggleStar = (capabilityId: string) => {
    setStars((current) => {
      const next = current.includes(capabilityId)
        ? current.filter((id) => id !== capabilityId)
        : [...current, capabilityId];
      localStorage.setItem(STAR_STORAGE_KEY, JSON.stringify(next));
      return next;
    });
  };

  const resetHome = () => {
    setQuery("");
    setSelectedCategories([]);
    setIsFilterOpen(false);
    if (window.location.hash !== "#/") {
      window.location.hash = "#/";
    } else {
      window.scrollTo({top: 0, behavior: "instant"});
    }
  };

  return (
    <div className="site">
      <a className="skip-link" href="#main-content">
        Skip to content
      </a>
      <SiteHeader database={database} route={route} onHomeReset={resetHome} />
      <SearchHero
        query={query}
        resultCount={filteredCapabilities.length}
        onChange={onSearchChange}
        onHomeReset={resetHome}
      />
      {route.name === "index" ? (
        <FeatureStrip
          database={database}
          route={route}
          query={query}
          resultCount={filteredCapabilities.length}
          isFilterOpen={isFilterOpen}
          selectedCategories={selectedCategories}
          onFilterOpenChange={setIsFilterOpen}
          onCategoryChange={(category, selected) => {
            setSelectedCategories((current) =>
              selected
                ? [...new Set([...current, category])]
                : current.filter((value) => value !== category),
            );
          }}
          onClearFilters={() => setSelectedCategories([])}
        />
      ) : null}

      {route.name === "index" ? (
        <IndexPage
          capabilities={filteredCapabilities}
          database={database}
          query={query}
          resultsMode={resultsMode}
          onResultsModeChange={setResultsMode}
          stars={stars}
          onToggleStar={toggleStar}
          gridMode={gridMode}
          onGridModeChange={setGridMode}
        />
      ) : null}

      {route.name === "capability" && capability ? (
        <CapabilityPage
          capability={capability}
          database={database}
          starred={stars.includes(capability.id)}
          onToggleStar={() => toggleStar(capability.id)}
          gridMode={gridMode}
          onGridModeChange={setGridMode}
        />
      ) : null}

      {route.name === "capability" && !capability ? (
        <main className="site-shell page-main" id="main-content">
          <Card>
            <Card.Header>
              <Card.Title>Capability not found</Card.Title>
              <Card.Description>
                This measurement may have moved or is not published.
              </Card.Description>
            </Card.Header>
            <Card.Footer>
              <Link href="#/">Return to the index</Link>
            </Card.Footer>
          </Card>
        </main>
      ) : null}

      {route.name === "changes" ? (
        <ChangesPage
          capabilities={allCapabilities}
          database={database}
        />
      ) : null}
      {route.name === "compare" ? (
        <ComparePage
          capabilities={allCapabilities}
          database={database}
        />
      ) : null}
      {route.name === "method" ? (
        <MethodPage database={database} />
      ) : null}

      <SiteFooter database={database} />
    </div>
  );
}
